config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :cost_centers
  resources :mail_codes
  resources :engagement_requests
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/department.rb
class Department < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true

  belongs_to :parent_department, optional: true, class_name: 'Department', foreign_key: 'parent_department_id'
  has_many :child_departments, class_name: 'Department', foreign_key: 'parent_department_id'

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :title
  belongs_to :job
  belongs_to :office
  belongs_to :department
end

app/models/engagement_request.rb
class EngagementRequest < ApplicationRecord
  include EngagementRequestsHelper

  enum engagement_type: [ :finger_estimate, :detailed_estimate, :scheduling, :rescue ]
  enum status: [ :validation, :submitted, :complete ]
  enum funding_method: [ :client, :initiative, :operations ]
  enum funding_status: [ :requested, :pending_approval, :approved, :budget ]
  enum priority: [ :high_priority, :medium_priority, :low_priority ]
  enum risk_rating: [ :high_risk, :medium_risk, :low_risk ]

  belongs_to :user, optional: true, class_name: 'Employee', foreign_key: 'user_id'
  belongs_to :requester, optional: true, class_name: 'Employee', foreign_key: 'requester_id'
  belongs_to :subject_expert, optional: true, class_name: 'Employee', foreign_key: 'subject_expert_id'
  belongs_to :sponsor, optional: true, class_name: 'Employee', foreign_key: 'sponsor_id'
  belongs_to :program, optional: true
  belongs_to :train, optional: true
  has_many :impacted_projects
  has_many :projects, through: :impacted_projects

  # I've seen things saying this should be in internationalization....
  # I can't be bothered to figure that out right now, this is just code! :)

  ENGAGEMENT_TYPES = {
      "finger_estimate" => 'Finger in the Air Estimate',
      "detailed_estimate" => 'Detailed Project Estimate',
      "scheduling" => 'Resource Scheduling',
      "rescue" => 'Problem Rescue'
  }

  STATUSES = {
      "validation" => 'Validation',
      "submitted" => 'Submitted',
      "estimated" => 'Estimated',
      "in_progress" => 'In Progress',
      "complete" => 'Complete'
  }

  FUNDING_METHODS = {
      "client" => 'Client Project',
      "initiative" => 'Internal Initiative',
      "operations" => 'Operations Budget',
  }

  FUNDING_STATUSES = {
      "requested" => 'Request Initiated',
      "pending_approval" => 'Pending Approval',
      "approved" => 'Fully Approved',
      "budget" => 'Budget Appropriated',
  }

  PRIORITIES = {
      "high_priority" => 'High',
      "medium_priority" => 'Medium',
      "low_priority" => 'Low',
  }

  RISK_RATINGS = {
      "high_risk" => 'High',
      "medium_risk" => 'Medium',
      "low_risk" => 'Low',
  }

end

app/models/impacted_project.rb
class ImpactedProject < ApplicationRecord
  # I couldn't get a multi-select option working for many to many, so this is here but not used :(
  belongs_to :project
  belongs_to :engagement_request
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/title.rb
class Title < ApplicationRecord
end

app/models/train.rb
class Train < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    # my employee structure seems slow, need to load joins to job/title/location
    @employees = Employee.all
    if params[:filter]
      filter = params[:filter].downcase
      # is this a good way?  I don't know!
      @employees = @employees.select do |employee|
        employee.first_name.downcase.include? filter or
            employee.last_name.downcase.include? filter or
            employee.email.downcase.include? filter or
            employee.title.name.downcase.include? filter or
            employee.job.name.downcase.include? filter or
            employee.office.street.downcase.include? filter or
            employee.office.city.downcase.include? filter or
            employee.office.country.downcase.include? filter or
            employee.department.name.downcase.include? filter or
            employee.department.description.downcase.include? filter
      end
      # this will render javascript to load list in browser
      @actions = params[:actions] || 'view'
      respond_to do |format|
        format.js { render partial: 'employee_loader' }
        format.html { render partial: 'employee_list' }
      end
    end
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # I'm not sure what this magic is doing, but it's needed for the json ajax call!
    def set_employee
      @employee = Employee.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mail_codes_controller.rb
class MailCodesController < ApplicationController
  include CodeGenerator

  # Generate a mail code, we've just made up some random format for fun
  def new
    @mail_code = new_mail_code
  end

  # Format: XX-XXX-NNNN-XX
  def new_mail_code
    [ random_chars(2), random_chars(3), random_digits(4), random_chars(2) ].join('-')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_generator.rb
# helpers for cost centers and mail codes
module CodeGenerator

  def random_digits(count)
    ((1..count).collect { rand(1...10) }.collect { |n| n.to_s }).join('')
  end

  def random_chars(count)
    ((1..count).collect { ("A".ord + rand(0...26)).chr }).join('')
  end

end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mail_codes_helper.rb
module MailCodesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/employees/_employee_filter_list.html.erb
<div class="container-fluid">
  <div class="row my-2">
    <h4 class="col-6"><%= title %></h4>
    <div class="col-6 text-right">
      <%= form_tag employees_path, method: :get, remote: true do %>
        <%= hidden_field_tag :actions, actions %>
        <%= label_tag :filter %>
        <%= text_field_tag :filter %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-2 font-weight-bold">First Name</div>
    <div class="col-2 font-weight-bold">Last Name</div>
    <div class="col-3 font-weight-bold">Email</div>
    <div class="col-3 font-weight-bold">Position</div>
    <div class="col-2"></div>
  </div>
</div>
<div id="employee_list">
  <%= render 'employees/employee_list', actions: actions %>
</div>

app/views/employees/_employee_list.html.erb
<div class="container-fluid mb-2">
  <% @employees.each do |employee| %>
    <div class="row">
      <div class="col-2"><%= employee.first_name %></div>
      <div class="col-2"><%= employee.last_name %></div>
      <div class="col-3"><%= employee.email %></div>
      <div class="col-3"><%= employee.title.name %>, <%= employee.job.name %></div>
      <div class="col-2">
        <%=
          case actions
            when :view, :view.to_s
              link_to 'View', employee_path(employee)
            when :select, :select.to_s
              button_tag 'Select', { "type" => 'button', "class" => "mb-1", "onclick" => 'selectEmployee(' + employee.id.to_s + ');', "data-dismiss" => "modal" }
          end
        %>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/_employee_loader.js.erb
console.log('hello!')
{
    const results = document.querySelector('#employee_list');
    console.log('You rendered!');
    const rendered = "<%= escape_javascript(render 'employee_list', actions: @actions) %>";
    console.log(rendered);
    results.innerHTML = rendered;
}

app/views/employees/_employee_selector.html.erb
<%= form.fields_for employee_field, employee do |employee_form| %>
  <div class="container px-0">
    <div class="row pb-2">
      <div class="col-1 px-0 mr-2">First</div>
      <%= form.hidden_field employee_field.to_s + '_id', id: employee_field.to_s + '_id' %>
      <%= employee_form.text_field :first_name, class: 'col-3 mr-2', disabled: 'true', id: employee_field.to_s + '_first_name' %>
      <div class="col-1 px-0 mr-2">Last</div>
      <%= employee_form.text_field :last_name, class: 'col-3 mr-2', disabled: 'true', id: employee_field.to_s + '_last_name' %>
    </div>
    <div class="row">
      <div class="col-1 px-0 mr-2">E-Mail</div>
      <%= employee_form.text_field :email, class: 'col-5 mr-2', disabled: 'true', id: employee_field.to_s + '_email' %>
      <%= button_tag "Search", type: 'button', class: 'col-2 px-0 mr-2',
                     onclick: "showEmployeeSearch('" + employee_field.to_s + "', '" + title + "');" %>
      <%= button_tag "Clear", type: 'button', class: 'col-2 px-0 mr-2',
                     onclick: "clearEmployee('" + employee_field.to_s + "');" %>
    </div>
  </div>
<% end %>

app/views/employees/_employee_selector_popup.html.erb
<div class="modal" id="employeeSelectorModal" tabindex="-1" role="dialog" aria-labelledby="#employeeSelectorModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="employeeSelectorModalLabel">Select Employee</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'employees/employee_filter_list', title: '', actions: :select %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/employees/_test.html.erb
<div>
  <b>This is a fucking test</b>
</div>

app/views/employees/index.html.erb
<%= render 'home/header' %>
<%= render 'employee_filter_list', title: 'Employee Directory', actions: :view %>

app/views/employees/show.html.erb
<%= render 'home/header' %>
<div class="container-fluid m-2 text-center">
  <div class="row">
    <h4 class="col-6"><%= @employee.first_name %> <%= @employee.last_name %></h4>
  </div>
  <div class="row">
    <h5 class="col-6"><%= @employee.title.name %>, <%= @employee.job.name %></h5>
  </div>
  <div class="row">
    <div class="col-3 text-right">
      Organization:
    </div>
    <div class="col-3 text-left">
      <%= @employee.department.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 text-right">
      Cost Center:
    </div>
    <div class="col-3 text-left">
      <%= @employee.department.cost_center %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 text-right">
      Location:
    </div>
    <div class="col-3 text-left">
      <%= @employee.office.street %>
      <br>
      <%= @employee.office.city %><%= ', ' + @employee.office.state if @employee.office.state %>
      <br>
      <%= @employee.office.country %>
    </div>
  </div>
  <div class="row">
    <div class="col-3 text-right">
      Mail Code:
    </div>
    <div class="col-3 text-left">
      <%= @employee.office.mail_code %>
    </div>
  </div>
</div>