config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :cost_centers
  resources :mail_codes
  resources :engagement_requests
  root 'home#index'
end

app/models/department.rb
class Department < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true

  belongs_to :parent_department, optional: true, class_name: 'Department', foreign_key: 'parent_department_id'
  has_many :child_departments, class_name: 'Department', foreign_key: 'parent_department_id'

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    # we are assuming Board of Directors (top level) is #1
    @department = Department.find(1)
  end

  def new
    @department = Department.new
    # departments is used for parent department selector
    @departments = Department.all
  end

  def edit
    id = params[:id]
    if ["1", "2"].include? id
      # don't allow edit to board and c-suite
      redirect_to departments_path
    else
      @department = Department.find(id)
      # departments is used for parent department selector
      @departments = Department.all
    end
  end

  def create
    @department = Department.new(department_params)
    # make sure a cost center value is set
    @department.cost_center = CostCentersController.new.new_cost_center if @department.cost_center.blank?
    if @department.save
      redirect_to departments_path
    else
      # departments is used for parent department selector
      @departments = Department.all
      render 'new'
    end
  end

  def update
    id = params[:id]
    if ["1", "2"].include? id
      # don't allow edit to board and c-suite
      redirect_to departments_path
    else
      @department = Department.find(params[:id])
      # departments is used for parent department selector when rendering edit
      @departments = Department.all
      if @department.id.to_s == params[:department][:parent_department_id]
        @department.errors.add(:parent_department_id, "can't be it's own parent")
        render 'edit'
      elsif detect_loop
        @department.errors.add(:parent_department_id, "can't be a descendent from this department")
        render 'edit'
      elsif @department.update(department_params)
        redirect_to departments_path
      else
        render 'edit'
      end
    end
  end

  private

    def department_params
      params.require(:department).permit(:name, :description, :cost_center, :parent_department_id)
    end

    def detect_loop
      # validate that we are not creating a loop!
      parents = [params[:id].to_i]
      parent_id = params[:department][:parent_department_id].to_i
      parent = Department.find(parent_id)
      while true
        if parent.id == 1
          # found the board, this is ok
          return false
        elsif parents.include? parent.id
          return true
        end
        parents.append parent.id
        parent = parent.parent_department
      end
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_with model: @department, local: true, class: 'container-fluid' do |form| %>

  <% if @department.errors.any? %>
    <div class="row mb-2">
      <div class="col-12">
        <ul>
          <% @department.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row mb-2">
    <%= form.label :name, class: 'col-2' %>
    <%= form.text_field :name, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :description, class: 'col-2' %>
    <%= form.text_field :description, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :parent_department_id, class: 'col-2' %>
    <%= form.select :parent_department_id,
                    options_for_select(@departments.collect { |department| [ department.name, department.id ] },
                                       @department.parent_department_id || params[:parent_department_id]) %>
  </div>

  <div class="row mb-2">
    <%= form.label :cost_center, class: 'col-2' %>
    <div class="col-8 p-0">
      <%= form.text_field :cost_center, id: 'cost_center', readonly: true %>
      <%= button_tag 'Generate', type: 'button', onclick: 'generate_cost_center()' %>
    </div>
  </div>

  <div class="row">
    <div class="col-10 pr-0">
      <div class="float-right mb-5">
        <%= form.submit %>
      </div>
    </div>
  </div>

<% end %>

app/views/departments/edit.html.erb
<%= render 'home/header' %>
<h4 class="m-2">Edit Department</h4>
<%= render 'form' %>

app/views/departments/index.html.erb
<%= render 'home/header' %>
<h4 class="m-2">Organization Hierarchy</h4>
<div class="container-fluid">
  <div class="row">
    <div class="col-2 font-weight-bold">Name</div>
    <div class="col-4 font-weight-bold">Description</div>
    <div class="col-2 font-weight-bold">Cost Center</div>
    <div class="col-2 font-weight-bold">Actions</div>
  </div>
</div>
<% def render_department(department) %>
  <div class="container-fluid mb-2">
    <div class="row my-1">
      <div class="col-2"><%= department.name %></div>
      <div class="col-4"><%= department.description %></div>
      <div class="col-2"><%= department.cost_center %></div>
      <div class="col-4">
        <%= link_to 'Edit', edit_department_path(department), class: 'btn btn-success' unless [1, 2].include?(department.id) %>
        <%= link_to 'Create Sub-Department',
                    new_department_path + '?parent_department_id=' + department.id.to_s,
                    class: 'btn btn-success'
        %>
      </div>
    </div>
    <% if department.child_departments.any? %>
      <div class="row">
        <div class="col-12">
          <% department.child_departments.each do |child_department| %>
            <%= render_department(child_department) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<%  nil %>
<% end %>
<%= render_department(@department) %>
<% if false %>
<%= link_to 'Generate Seed Code', { :format => :text }, class: 'btn btn-success m-2' %>
<% end %>

app/views/departments/index.text.erb
<% def render_department(department) # this generates code for the seed file, spacing intentionally compact! %>
department<%= department.id %> = Department.create(name: '<%= department.name %>',
                                description: '<%= department.description %>',
                                cost_center: '<%= department.cost_center %>',
                                parent_department_id: <%= (department.parent_department && 'department' + department.parent_department.id.to_s + '.id') || 'nil' %>)
    <% if department.child_departments.any? %>
      <% department.child_departments.each do |child_department| %>
<%= render_department(child_department) %><% end %><% end %><% nil %><% end %>
<%= render_department(@department) %>

app/views/departments/new.html.erb
<%= render 'home/header' %>
<h4 class="m-2">New Department</h4>
<%= render 'form' %>