config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :cost_centers
  resources :mail_codes
  resources :engagement_requests
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/department.rb
class Department < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true

  belongs_to :parent_department, optional: true, class_name: 'Department', foreign_key: 'parent_department_id'
  has_many :child_departments, class_name: 'Department', foreign_key: 'parent_department_id'

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :title
  belongs_to :job
  belongs_to :office
  belongs_to :department
end

app/models/engagement_request.rb
class EngagementRequest < ApplicationRecord
  include EngagementRequestsHelper

  enum engagement_type: [ :finger_estimate, :detailed_estimate, :scheduling, :rescue ]
  enum status: [ :validation, :submitted, :complete ]
  enum funding_method: [ :client, :initiative, :operations ]
  enum funding_status: [ :requested, :pending_approval, :approved, :budget ]
  enum priority: [ :high_priority, :medium_priority, :low_priority ]
  enum risk_rating: [ :high_risk, :medium_risk, :low_risk ]

  belongs_to :user, optional: true, class_name: 'Employee', foreign_key: 'user_id'
  belongs_to :requester, optional: true, class_name: 'Employee', foreign_key: 'requester_id'
  belongs_to :subject_expert, optional: true, class_name: 'Employee', foreign_key: 'subject_expert_id'
  belongs_to :sponsor, optional: true, class_name: 'Employee', foreign_key: 'sponsor_id'
  belongs_to :program, optional: true
  belongs_to :train, optional: true
  has_many :impacted_projects
  has_many :projects, through: :impacted_projects

  # I've seen things saying this should be in internationalization....
  # I can't be bothered to figure that out right now, this is just code! :)

  ENGAGEMENT_TYPES = {
      "finger_estimate" => 'Finger in the Air Estimate',
      "detailed_estimate" => 'Detailed Project Estimate',
      "scheduling" => 'Resource Scheduling',
      "rescue" => 'Problem Rescue'
  }

  STATUSES = {
      "validation" => 'Validation',
      "submitted" => 'Submitted',
      "estimated" => 'Estimated',
      "in_progress" => 'In Progress',
      "complete" => 'Complete'
  }

  FUNDING_METHODS = {
      "client" => 'Client Project',
      "initiative" => 'Internal Initiative',
      "operations" => 'Operations Budget',
  }

  FUNDING_STATUSES = {
      "requested" => 'Request Initiated',
      "pending_approval" => 'Pending Approval',
      "approved" => 'Fully Approved',
      "budget" => 'Budget Appropriated',
  }

  PRIORITIES = {
      "high_priority" => 'High',
      "medium_priority" => 'Medium',
      "low_priority" => 'Low',
  }

  RISK_RATINGS = {
      "high_risk" => 'High',
      "medium_risk" => 'Medium',
      "low_risk" => 'Low',
  }

end

app/models/impacted_project.rb
class ImpactedProject < ApplicationRecord
  # I couldn't get a multi-select option working for many to many, so this is here but not used :(
  belongs_to :project
  belongs_to :engagement_request
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/title.rb
class Title < ApplicationRecord
end

app/models/train.rb
class Train < ApplicationRecord
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    # my employee structure seems slow, need to load joins to job/title/location
    @employees = Employee.all
    if params[:filter]
      filter = params[:filter].downcase
      # is this a good way?  I don't know!
      @employees = @employees.select do |employee|
        employee.first_name.downcase.include? filter or
            employee.last_name.downcase.include? filter or
            employee.email.downcase.include? filter or
            employee.title.name.downcase.include? filter or
            employee.job.name.downcase.include? filter or
            employee.office.street.downcase.include? filter or
            employee.office.city.downcase.include? filter or
            employee.office.country.downcase.include? filter or
            employee.department.name.downcase.include? filter or
            employee.department.description.downcase.include? filter
      end
      # this will render javascript to load list in browser
      @actions = params[:actions] || 'view'
      respond_to do |format|
        format.js { render partial: 'employee_loader' }
        format.html { render partial: 'employee_list' }
      end
    end
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # I'm not sure what this magic is doing, but it's needed for the json ajax call!
    def set_employee
      @employee = Employee.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mail_codes_controller.rb
class MailCodesController < ApplicationController
  include CodeGenerator

  # Generate a mail code, we've just made up some random format for fun
  def new
    @mail_code = new_mail_code
  end

  # Format: XX-XXX-NNNN-XX
  def new_mail_code
    [ random_chars(2), random_chars(3), random_digits(4), random_chars(2) ].join('-')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_generator.rb
# helpers for cost centers and mail codes
module CodeGenerator

  def random_digits(count)
    ((1..count).collect { rand(1...10) }.collect { |n| n.to_s }).join('')
  end

  def random_chars(count)
    ((1..count).collect { ("A".ord + rand(0...26)).chr }).join('')
  end

end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mail_codes_helper.rb
module MailCodesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/home/_header.html.erb
<header class="container-fluid py-2 bg-primary text-light">
  <div class="row">
    <h3 class="col-10 text-center">
      Jay Crowley Engagement Request Process
    </h3>
    <small class="col-2 text-right">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#whatIsThisModal">What is This?</button>
    </small>
  </div>
</header>
<div class="modal fade" id="whatIsThisModal" tabindex="-1" role="dialog" aria-labelledby="#whatIsThisModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="whatIsThisModalLabel">What is This?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          I work in the tech division of a very large organization.
          As with many very large organizations, there is more than a bit of bureaucracy.
          This web app is roughly based on an actual form in the organization for requesting
          technical help with new projects.  The form itself appeared to be designed so
          that it could not be completed properly.  This allowed the receivers of said form
          to get out of doing any actual work by rejecting all requests.
        </p>
        <p>
          I've been there a long time, and have touched many things, so I often get
          requests out of the blue, from random places in the organization.
          I was joking with colleagues about implementing a request form for myself,
          similar to the forms found for other departments, and this site was born.
          My form is quite a bit prettier than the actual form, believe it or not!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-sm navbar-light border-bottom">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%=
          # helper to set class of nav item so active is current url
          # is this a good way to do this?  not really sure, but works great!
          def nav_class(path)
            if request.path == path
              'nav-link active'
            else
              'nav-link'
            end
          end

          link_to "Home", root_path, class: nav_class(root_path)
        %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Request', new_engagement_request_path, class: nav_class(new_engagement_request_path) %>
      </li>
      <li class="nav-item">
        <%= link_to 'Request Status', engagement_requests_path, class: nav_class(engagement_requests_path) %>
      </li>
      <li class="nav-item">
        <%= link_to 'Employee Directory', employees_path, class: nav_class(employees_path) %>
      </li>
      <li class="nav-item">
        <%= link_to 'Organization Hierarchy', departments_path, class: nav_class(departments_path) %>
      </li>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<%= render 'header' %>
<h4 class="m-2">Create a New Engagement Request</h4>
<p class="m-2 pb-2">
  You have a new project idea, and you need help.  Here's how to engage Jay Crowley for expert project management advice.
</p>
<div class="container-fluid">
  <div class="row my-2">
    <div class="col-sm-2">
      <%= link_to 'Finger in the Air Estimation', new_engagement_request_path + '?engagement_type=finger_estimate', class: 'btn btn-primary btn-lg btn-block' %>
    </div>
    <div class="col-sm-10">
      Request a rough estimation for a project idea that you had a dream about last night.  You aren't sure what it means.
      You have no idea if it's feasible.  I will tell you it is not, and what is possible, and charge good money for that expertise.
    </div>
  </div>
  <div class="row my-2">
    <div class="col-sm-2">
      <%= link_to 'Detailed Project Estimates', new_engagement_request_path + '?engagement_type=detailed_estimate', class: 'btn btn-success btn-lg btn-block' %>
    </div>
    <div class="col-sm-10">
      After you have ignored the finger in the air estimate, and raised money, use this.
      Get a more in-depth analysis of the work that will need to be performed, and time, resource and funding estimates.
    </div>
  </div>
  <div class="row my-2">
    <div class="col-sm-2">
      <%= link_to 'Resource Scheduling', new_engagement_request_path + '?engagement_type=scheduling', class: 'btn btn-warning btn-lg btn-block' %>
    </div>
    <div class="col-sm-10">
      If you have managed to make it past the first two estimate steps, feel free to schedule time to do your work.
      We will put together a team of experts (mainly college graduates, billed at extortionate rates.)
      You will need to have approved funding in place!
    </div>
  </div>
  <div class="row my-2">
    <div class="col-sm-2">
      <%= link_to 'Problem Rescue', new_engagement_request_path + '?engagement_type=rescue', class: 'btn btn-danger btn-lg btn-block' %>
    </div>
    <div class="col-sm-10">
      You've gone ahead and tried to do it yourself.  You are stuck.  You need my expertise to get out of a bind.
      Use this for small, short notice tasks or advice.  Billed at double!
    </div>
  </div>
</div>