config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :cost_centers
  resources :mail_codes
  resources :engagement_requests
  root 'home#index'
end

app/models/engagement_request.rb
class EngagementRequest < ApplicationRecord
  include EngagementRequestsHelper

  enum engagement_type: [ :finger_estimate, :detailed_estimate, :scheduling, :rescue ]
  enum status: [ :validation, :submitted, :complete ]
  enum funding_method: [ :client, :initiative, :operations ]
  enum funding_status: [ :requested, :pending_approval, :approved, :budget ]
  enum priority: [ :high_priority, :medium_priority, :low_priority ]
  enum risk_rating: [ :high_risk, :medium_risk, :low_risk ]

  belongs_to :user, optional: true, class_name: 'Employee', foreign_key: 'user_id'
  belongs_to :requester, optional: true, class_name: 'Employee', foreign_key: 'requester_id'
  belongs_to :subject_expert, optional: true, class_name: 'Employee', foreign_key: 'subject_expert_id'
  belongs_to :sponsor, optional: true, class_name: 'Employee', foreign_key: 'sponsor_id'
  belongs_to :program, optional: true
  belongs_to :train, optional: true
  has_many :impacted_projects
  has_many :projects, through: :impacted_projects

  # I've seen things saying this should be in internationalization....
  # I can't be bothered to figure that out right now, this is just code! :)

  ENGAGEMENT_TYPES = {
      "finger_estimate" => 'Finger in the Air Estimate',
      "detailed_estimate" => 'Detailed Project Estimate',
      "scheduling" => 'Resource Scheduling',
      "rescue" => 'Problem Rescue'
  }

  STATUSES = {
      "validation" => 'Validation',
      "submitted" => 'Submitted',
      "estimated" => 'Estimated',
      "in_progress" => 'In Progress',
      "complete" => 'Complete'
  }

  FUNDING_METHODS = {
      "client" => 'Client Project',
      "initiative" => 'Internal Initiative',
      "operations" => 'Operations Budget',
  }

  FUNDING_STATUSES = {
      "requested" => 'Request Initiated',
      "pending_approval" => 'Pending Approval',
      "approved" => 'Fully Approved',
      "budget" => 'Budget Appropriated',
  }

  PRIORITIES = {
      "high_priority" => 'High',
      "medium_priority" => 'Medium',
      "low_priority" => 'Low',
  }

  RISK_RATINGS = {
      "high_risk" => 'High',
      "medium_risk" => 'Medium',
      "low_risk" => 'Low',
  }

end

app/controllers/engagement_requests_controller.rb
class EngagementRequestsController < ApplicationController
  include CodeGenerator

  def index
    @engagement_requests = EngagementRequest.all
    # check estimates to update
    @engagement_requests.each { |request| request.estimate }
  end

  def show
    @engagement_request = EngagementRequest.find(params[:id])
    # check estimate to update
    @engagement_request.estimate
  end

  def new
    @engagement_request = EngagementRequest.new
    # used for lookups
    @programs = Program.all
    @projects = Project.all
    @trains = Train.all
    @employees = Employee.all
  end

  def edit
    @engagement_request = EngagementRequest.find(params[:id])
    # used for lookups
    @programs = Program.all
    @projects = Project.all
    @trains = Train.all
    @employees = Employee.all
  end

  # In theory, the UI let's this always succeed (I suppose someone could post bad foreign keys)
  # We just make sure all the validations try to keep the status in Validation status.
  def create
    @engagement_request = EngagementRequest.new(engagement_request_params)
    @engagement_request.engagement_id = new_engagement_id
    @engagement_request.validate
    @engagement_request.save
    redirect_to @engagement_request
  end

  def update
    @engagement_request = EngagementRequest.find(params[:id])
    @engagement_request.update engagement_request_params
    @engagement_request.validate
    @engagement_request.save
    redirect_to @engagement_request
  end

  # once again, making up a format so we always have an identifier visible
  # Since the create form lets you create a completely blank item
  # Format: XX-NN-XXXX-XX
  def new_engagement_id
    [ random_chars(2), random_digits(2), random_chars(4), random_chars(2) ].join('-')
  end

  private

    def engagement_request_params
      params.require(:engagement_request).permit(
          :engagement_type, :project_name,
          :requester_id, :subject_expert_id, :sponsor_id,
          :vision, :goal, :description, :scope, :advice_required,
          :program_id, :train_id, :project_ids,
          :funding_method, :cost_center, :funding_status, :budget_allocated,
          :priority, :start_date, :end_date, :risk_rating, :risks, :projected_revenue
      )
    end
end

app/helpers/engagement_requests_helper.rb
require 'set'
include ActionView::Helpers::NumberHelper

module EngagementRequestsHelper

  # I'm presuming this module is for mix in functions
  # I'm going to use it for my validations, this is mixed into the model
  # The point of this function is to be as annoying as possible, and prevent success
  # A demo that is designed to be annoying may have been a bad idea!
  def validate
    # assume we are invalid, unless we manage to pass everything
    self.status = :validation
    self.validations = nil

    if self.validate_required
      # perform other validations
      self.validate_contacts
      self.validate_project
      self.validate_funding
      self.validate_time_to_market

      if self.validations.nil?
        # success!  miraculous!
        self.status = :submitted
      else
        # shuffle and truncate errors
        validations = self.validations.split('|')
        validations.shuffle!
        if validations.size > 5
          validations = validations[0...5]
          validations.append('More than 5 validation errors. Fix errors to see further validations')
        end
        self.validations = validations.join('|')
      end
    end
  end

  # make sure all user entered fields are filled with something
  def validate_required
    [
        :project_name,
        :status,
        :requester_id,
        :subject_expert_id,
        :sponsor_id,
        :vision,
        :goal,
        :description,
        :scope,
        :advice_required,
        :program_id,
        :train_id,
        :funding_method,
        :cost_center,
        :funding_status,
        :budget_allocated,
        :priority,
        :start_date,
        :end_date,
        :risk_rating,
        :risks,
        :projected_revenue,
    ].each do |field|
      if self.attributes[field.to_s].nil? || self.attributes[field.to_s].blank?
        # intentionally vague!
        add_validation 'All fields are required to perform further validations'
        return false
      end
    end
    true
  end

  # make sure employees meet random requirements
  def validate_contacts
    # we assume they are set at this point
    # contacts are unique
    contacts = [ self.requester, self.subject_expert, self.sponsor ]
    if Set.new(contacts).length != contacts.length
      add_validation 'All contacts must be unique'
    end

    # sponsor should be higher than expert, and expert higher than requester
    # ranks are reversed, rank 1 is top (board chairman)
    if self.sponsor.title.rank >= self.subject_expert.title.rank
      add_validation 'Sponsor should be a higher rank than the Subject Expert'
    end
    if self.subject_expert.title.rank >= self.requester.title.rank
      add_validation 'Subject Expert should be a higher rank than the Requester'
    end

    # contacts are co-located!
    if Set.new(contacts.map { |contact| contact.office.mail_code }).length > 1
      add_validation 'All contacts should be co-located'
    end
  end

  # validates the project description fields.
  def validate_project

    # project name should be 10 to 30 length, and 5 words or fewer
    validate_length_words 'Project Name', self.project_name, 10, 30, 0, 5

    # vision should be 1 sentence
    validate_sentences_length 'Vision', self.vision, 30, 100, 1

    # goal should be 1 sentence
    validate_sentences_length 'Goal', self.goal, 30, 100, 1

    # description, and scope should be 5 sentences!
    validate_sentences_length 'Description', self.description, 100, 500, 5
    validate_sentences_length 'Scope', self.scope, 100, 500, 5

    # advice needed
    validate_sentences_length 'Advice Required', self.advice_required, 50, 200, 3

    # randomize program and train complaints!
    validate_random_day 'Program', self.program.name
    validate_random_day 'Train', self.train.name
  end

  # validate the funding section
  def validate_funding
    # randomize funding method!
    validate_random_day 'Funding Method', EngagementRequest::FUNDING_METHODS[self.funding_method]

    # sponsor is funding it!
    if self.cost_center != self.sponsor.department.cost_center
      add_validation "Cost Center should match the Sponsor's cost center"
    end

    # detailed estimate must be funding approved!
    if self.detailed_estimate? && ! (self.approved? || self.budget?)
      add_validation EngagementRequest::ENGAGEMENT_TYPES[self.engagement_type] + ' must have budget ' +
                         EngagementRequest::FUNDING_STATUSES["approved"] + ' or ' +
                         EngagementRequest::FUNDING_STATUSES["budget"]
    end
    # scheduling or rescue must have budget!
    if (self.scheduling? || self.rescue?) && ! self.budget?
      add_validation EngagementRequest::ENGAGEMENT_TYPES[self.engagement_type] + ' must have ' +
                         EngagementRequest::FUNDING_STATUSES["budget"]
    end

    # must have a decent budget!
    if self.budget_allocated < 100_000
      add_validation 'Projects with a budget of less than $100,000 are not accepted'
    end
  end

  LEAD_TIME = {
      "high_priority" => 30,
      "medium_priority" => 60,
      "low_priority" => 90
  }

  RISK_REWARD = {
      "high_risk" => 5_000_000,
      "medium_risk" => 2_000_000,
      "low_risk" => 500_000,
  }

  # validate time to market values!
  def validate_time_to_market
    # lead time based on priority!
    today = Date.today
    days = (self.start_date - today).to_i
    if days < LEAD_TIME[self.priority]
      add_validation 'Start date must be at least ' + LEAD_TIME[self.priority].to_s + ' days in advance for ' +
                         EngagementRequest::PRIORITIES[self.priority] + ' priority'
    end

    # 30 day minimum!
    length = (self.end_date - self.start_date).to_i
    if length < 30
      add_validation 'Projects with a length of less than 30 days will not be considered'
    end

    # must start on a Monday and end on a Friday
    if self.start_date.wday != 1
      add_validation 'Start Date must be a Monday'
    end
    if self.end_date.wday != 5
      add_validation 'End Date must be a Friday'
    end

    # cost reduction projects!
    cost_reduction = ['Operations Streamlining', 'Manufacturing Efficiency'].include? self.program.name
    if cost_reduction && self.projected_revenue != 0
      add_validation self.program.name + ' is not expected to generate revenue'
    end
    if cost_reduction && ! self.low_risk?
      add_validation self.program.name + ' projects must be low risk'
    end

    # potential profit!
    profit = self.projected_revenue - self.budget_allocated
    if ! cost_reduction && profit < RISK_REWARD[self.risk_rating]
      add_validation EngagementRequest::RISK_RATINGS[self.risk_rating] +
                         ' risk projects should be expected to produce at least ' +
                         number_to_currency(RISK_REWARD[self.risk_rating]) + ' profit'
    end

    # risks should be defined! 5 sentences!
    validate_sentences_length 'Risks', self.risks, 100, 500, 5
  end

  # takes a random chance to invalidate a selection for day of week
  def validate_random_day(name, value)
    now = Time.new
    if rand(0...7) == now.wday
      add_validation name + ' ' + value + ' is not considered on ' + now.strftime("%A") + '.  Try another time'
    end
  end

  def validate_length_words(name, value, min_length, max_length, min_words, max_words)
    validate_words name, value, min_words, max_words
    validate_length name, value, min_length, max_length
  end

  def validate_words(name, value, min_words, max_words)
    words = value.split
    word_count = words.size
    word_length = words.size > 0 ? words.map { |word| word.length }.sum / words.size : 0
    if word_count < min_words
      add_validation name + ' should be at least ' + min_words.to_s + ' words'
    elsif word_count > max_words
      add_validation name + ' should be fewer than ' + max_words.to_s + ' words'
    elsif word_length < 5
      add_validation name + ' should have an average word length of 5 or more'
    end
  end

  def validate_sentences_length(name, value, min_length, max_length, min_sentences)
    validate_length name, value, min_length, max_length
    validate_sentences name, value, min_sentences
  end

  def validate_length(name, value, min_length, max_length)
    if value.length < min_length
      add_validation name + ' should be at least ' + min_length.to_s + ' characters'
    elsif value.length > max_length
      add_validation name + ' should be fewer than ' + (max_length + 1).to_s + ' characters'
    end
  end

  def validate_sentences(name, value, min_count)
    sentences = value.split('.')
    words = sentences.map { |sentence| sentence.split.size }.select { |words| words > 5 }
    if words.size < min_count
      add_validation name + ' should have at least ' + min_count.to_s + ' full ' + 'sentence'.pluralize(min_count)
    elsif not value.end_with?('.')
      add_validation name + ' should ' + (min_count > 1 ? 'end with' : 'be a') + ' complete sentence'
    end
  end

  def add_validation(message)
    if self.validations.nil?
      self.validations = message
    else
      self.validations += '|' + message
    end
  end

  # this method creates a fake estimation on submitted requests if they are more than 5 minutes old
  def estimate
    if self.submitted? && (Time.now - self.updated_at) > 5 * 60
      # re-initialize the estimates
      self.estimated_cost = nil
      self.estimated_duration = nil
      # only estimate projects with a budget of $200K!  because why bother!
      budget = self.budget_allocated
      if budget > 200_000
        # give them a 50/50
        if rand > 0.5
          # estimate the number of college grads needed during the time frame + 30%
          # to consume the budget * 2
          days = ((self.end_date - self.start_date) * 1.3).ceil
          budget_per_day = budget * 2 / days
          student_per_day = 200 * 8 # $200/hour * 8 hours
          students = (budget_per_day / student_per_day).ceil

app/views/engagement_requests/_form.html.erb
<%= form_with model: @engagement_request, class: 'container-fluid' do |form| %>

  <% if @engagement_request.engagement_id %>

    <div class="row">
      <div class="col-2">Id</div>
      <div class="col-8">
        <%= @engagement_request.engagement_id %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">Status</div>
      <div class="col-8">
        <%= @engagement_request.status %>
      </div>
    </div>

  <% end %>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Contacts</h5>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :requester, class: 'col-2' %>
    <div class="col-8">
      <%= render 'employees/employee_selector', form: form,
                 employee_field: :requester, employee: @engagement_request.requester,
                 title: 'Select Requester' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :subject_expert, class: 'col-2' %>
    <div class="col-8">
      <%= render 'employees/employee_selector', form: form,
                 employee_field: :subject_expert, employee: @engagement_request.subject_expert,
                 title: 'Select Subject Expert' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :sponsor, class: 'col-2' %>
    <div class="col-8">
      <%= render 'employees/employee_selector', form: form,
                 employee_field: :sponsor, employee: @engagement_request.sponsor,
                 title: 'Select Sponsor' %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Project Definition</h5>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :engagement_type, class: 'col-2' %>
    <%= form.select :engagement_type,
                    options_for_select(EngagementRequest.engagement_types.collect do |key, value|
                                        [ EngagementRequest::ENGAGEMENT_TYPES[key], key ]
                                       end,
                                       @engagement_request.engagement_type || params[:engagement_type]) %>
  </div>

  <div class="row mb-2">
    <%= form.label :project_name, class: 'col-2' %>
    <%= form.text_field :project_name, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :vision, class: 'col-2' %>
    <%= form.text_area :vision, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :goal, class: 'col-2' %>
    <%= form.text_area :goal, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :description, class: 'col-2' %>
    <%= form.text_area :description, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :scope, class: 'col-2' %>
    <%= form.text_area :scope, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :advice_required, class: 'col-2' %>
    <%= form.text_area :advice_required, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :program_id, class: 'col-2' %>
    <%= form.select :program_id, @programs.collect { |program| [ program.name, program.id ] }, { include_blank: true } %>
  </div>

  <div class="row mb-2">
    <%= form.label :train_id, class: 'col-2' %>
    <%= form.select :train_id, @trains.collect { |train| [ train.name, train.id ] }, { include_blank: true } %>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Funding</h5>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :funding_method, class: 'col-2' %>
    <%= form.select :funding_method,
                    options_for_select(EngagementRequest.funding_methods.collect do |key, value|
                                         [ EngagementRequest::FUNDING_METHODS[key], key ]
                                       end,
                                       @engagement_request.funding_method),
                    { include_blank: true } %>
  </div>

  <div class="row mb-2">
    <%= form.label :cost_center, class: 'col-2' %>
    <%= form.text_field :cost_center, class: 'col-4' %>
  </div>

  <div class="row mb-2">
    <%= form.label :funding_status, class: 'col-2' %>
    <%= form.select :funding_status,
                    options_for_select(EngagementRequest.funding_statuses.collect do |key, value|
                                         [ EngagementRequest::FUNDING_STATUSES[key], key ]
                                       end,
                                       @engagement_request.funding_status),
                    { include_blank: true } %>
  </div>

  <div class="row mb-2">
    <%= form.label :budget_allocated, class: 'col-2' %>
    <%= form.number_field :budget_allocated, class: 'col-2' %>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Time to Market</h5>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :priority, class: 'col-2' %>
    <%= form.select :priority,
                    options_for_select(EngagementRequest.priorities.collect do |key, value|
                                         [ EngagementRequest::PRIORITIES[key], key ]
                                       end,
                                       @engagement_request.priority),
                    { include_blank: true } %>
  </div>

  <div class="row mb-2">
    <%= form.label :start_date, class: 'col-2' %>
    <div class="col-4 px-0">
      <%= form.date_select :start_date, class: 'col-2' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :end_date, class: 'col-2' %>
    <div class="col-4 px-0">
      <%= form.date_select :end_date, class: 'col-2' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :risk_rating, class: 'col-2' %>
    <%= form.select :risk_rating,
                    options_for_select(EngagementRequest.risk_ratings.collect do |key, value|
                                         [ EngagementRequest::RISK_RATINGS[key], key ]
                                       end,
                                       @engagement_request.risk_rating),
                    { include_blank: true } %>
  </div>

  <div class="row mb-2">
    <%= form.label :risks, class: 'col-2' %>
    <%= form.text_area :risks, class: 'col-8' %>
  </div>

  <div class="row mb-2">
    <%= form.label :projected_revenue, class: 'col-2' %>
    <%= form.number_field :projected_revenue, class: 'col-2' %>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Validations Summary</h5>
      <% if @engagement_request.validations %>
        <ul class="text-danger">
          <% @engagement_request.validations.split('|').each do |validation| %>
            <li><%= validation %></li>
          <% end %>
        </ul>
      <% elsif @engagement_request.status.nil? %>
        <p>Validations will appear here when you submit the form.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-10 pr-0">
      <div class="float-right mb-5">
        <%= form.submit 'Save Engagement Request', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>
<%= render 'employees/employee_selector_popup' %>

app/views/engagement_requests/show.html.erb
<%= render 'home/header' %>
<h4 class="m-2">View Engagement Request</h4>
<div class="container-fluid">
  <div class="row">
    <div class="col-2">Id</div>
    <div class="col-8"><%= @engagement_request.engagement_id %></div>
  </div>
  <div class="row">
    <div class="col-2">Status</div>
    <div class="col-2"><%= EngagementRequest::STATUSES[@engagement_request.status] %></div>
  </div>
  <% if @engagement_request.submitted? %>
    <div class="row">
      <div class="col-8">
        Congratulations, you have passed all validations.
        Your request will be reviewed shortly.
        Check back in a few minutes.
      </div>
    </div>
  <% end %>

  <% if @engagement_request.complete? %>
    <div class="row">
      <div class="col-12">
        <hr>
        <h5>Review Results</h5>
      </div>
    </div>
    <% if @engagement_request.estimated_cost.nil? %>
      <div class="row">
        <div class="col-2">Review Notes</div>
        <div class="col-4"><%= @engagement_request.estimate_breakdown %></div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-12">
          Jay has deemed your project feasible, with a small increased budget and time frame as below.
          He will be in contact before the start of the project.
        </div>
      </div>
      <div class="row">
        <div class="col-2">Estimated Cost</div>
        <div class="col-4"><%= number_to_currency(@engagement_request.estimated_cost) %></div>
      </div>
      <div class="row">
        <div class="col-2">Estimate Breakdown</div>
        <div class="col-4"><%= @engagement_request.estimate_breakdown %></div>
      </div>
      <div class="row">
        <div class="col-2">Estimated End Date</div>
        <div class="col-4"><%= @engagement_request.estimated_duration %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Contacts</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Requester</div>
    <div class="col-8">
      <% if @engagement_request.requester %>
        <div class="container">
          <div class="row">
            <div class="col-3">
              <%= @engagement_request.requester.first_name %>
              <%= @engagement_request.requester.last_name %>
            </div>
            <div class="col-3"><%= @engagement_request.requester.title.name %></div>
            <div class="col-3"><%= @engagement_request.requester.job.name %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Subject Expert</div>
    <div class="col-8">
      <% if @engagement_request.subject_expert %>
        <div class="container">
          <div class="row">
            <div class="col-3">
              <%= @engagement_request.subject_expert.first_name %>
              <%= @engagement_request.subject_expert.last_name %>
            </div>
            <div class="col-3"><%= @engagement_request.subject_expert.title.name %></div>
            <div class="col-3"><%= @engagement_request.subject_expert.job.name %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Sponsor</div>
    <div class="col-8">
      <% if @engagement_request.sponsor %>
        <div class="container">
          <div class="row">
            <div class="col-3">
              <%= @engagement_request.sponsor.first_name %>
              <%= @engagement_request.sponsor.last_name %>
            </div>
            <div class="col-3"><%= @engagement_request.sponsor.title.name %></div>
            <div class="col-3"><%= @engagement_request.sponsor.job.name %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Project Definition</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Engagement Type</div>
    <div class="col-8"><%= EngagementRequest::ENGAGEMENT_TYPES[@engagement_request.engagement_type] %></div>
  </div>
  <div class="row">
    <div class="col-2">Project Name</div>
    <div class="col-8"><%= @engagement_request.project_name %></div>
  </div>
  <div class="row">
    <div class="col-2">Vision</div>
    <div class="col-8"><%= @engagement_request.vision %></div>
  </div>
  <div class="row">
    <div class="col-2">Goal</div>
    <div class="col-8"><%= @engagement_request.goal %></div>
  </div>
  <div class="row">
    <div class="col-2">Description</div>
    <div class="col-8"><%= @engagement_request.description %></div>
  </div>
  <div class="row">
    <div class="col-2">Scope</div>
    <div class="col-8"><%= @engagement_request.scope %></div>
  </div>
  <div class="row">
    <div class="col-2">Advice Required</div>
    <div class="col-8"><%= @engagement_request.advice_required %></div>
  </div>
  <div class="row">
    <div class="col-2">Program</div>
    <div class="col-8"><%= @engagement_request.program && @engagement_request.program.name %></div>
  </div>
  <div class="row">
    <div class="col-2">Train</div>
    <div class="col-8"><%= @engagement_request.train && @engagement_request.train.name %></div>
  </div>
  <% if false # never got this working, and project dont enough %>
  <div class="row">
    <div class="col-2">Impacted Projects</div>
    <div class="col-8">
      <%= @engagement_request.projects.collect { |project| project.name }.join(', ') %>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Funding</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Funding Method</div>
    <div class="col-8"><%= EngagementRequest::FUNDING_METHODS[@engagement_request.funding_method] %></div>
  </div>
  <div class="row">
    <div class="col-2">Cost Center</div>
    <div class="col-8"><%= @engagement_request.cost_center %></div>
  </div>
  <div class="row">
    <div class="col-2">Funding Status</div>
    <div class="col-8"><%= EngagementRequest::FUNDING_STATUSES[@engagement_request.funding_status] %></div>
  </div>
  <div class="row">
    <div class="col-2">Budget Allocated</div>
    <div class="col-8"><%= number_to_currency(@engagement_request.budget_allocated) %></div>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Time to Market</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-2">Priority</div>
    <div class="col-8"><%= EngagementRequest::PRIORITIES[@engagement_request.priority] %></div>
  </div>
  <div class="row">
    <div class="col-2">Start Date</div>
    <div class="col-8"><%= @engagement_request.start_date %></div>
  </div>
  <div class="row">
    <div class="col-2">End Date</div>
    <div class="col-8"><%= @engagement_request.end_date %></div>
  </div>
  <div class="row">
    <div class="col-2">Risk Rating</div>
    <div class="col-8"><%= EngagementRequest::RISK_RATINGS[@engagement_request.risk_rating] %></div>
  </div>
  <div class="row">
    <div class="col-2">Risks</div>
    <div class="col-8"><%= @engagement_request.risks %></div>
  </div>
  <div class="row">
    <div class="col-2">Projected Revenue</div>
    <div class="col-8"><%= number_to_currency(@engagement_request.projected_revenue) %></div>
  </div>

  <div class="row">
    <div class="col-12">
      <hr>
      <h5>Validations Summary</h5>
    </div>
  </div>
  <% if @engagement_request.validations %>
    <div class="row">
      <div class="col-12">
        <ul class="text-danger">
          <% @engagement_request.validations.split('|').each do |validation| %>
            <li><%= validation %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-10 pr-0">
      <div class="float-right mb-5">
        <%= link_to 'Edit', edit_engagement_request_path(@engagement_request), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>